In [8]:

import psycopg2.extras
from dotenv import load_dotenv
import os

In [3]:
load_dotenv()

conn = psycopg2.connect(
    host = os.getenv("DB_HOST"),
    port = os.getenv("DB_PORT"),
    dbname = os.getenv("DB_NAME"),
    user = os.getenv("DB_USER"),
    password = os.getenv("DB_PASSWORD")
)

print("Conexion exitosa")

Conexion exitosa

In [4]:
cursor = conn.cursor()

cursor.execute("SELECT * FROM ventas;")
filas = cursor.fetchall()

for fila in filas:
    print(fila)

(21, 'Ana', 'enero', 15000, 'norte', 'laptop')
(22, 'Luis', 'enero', 8000, 'sur', 'mouse')
(23, 'Ana', 'febrero', 20000, 'norte', 'laptop')
(24, 'Eva', 'enero', 12000, 'norte', 'teclado')
(25, 'Luis', 'febrero', 9500, 'sur', 'monitor')
(26, 'Ana', 'marzo', 18000, 'norte', 'laptop')
(27, 'Eva', 'febrero', 15000, 'norte', 'monitor')
(28, 'Luis', 'marzo', 11000, 'sur', 'laptop')
(29, 'Eva', 'marzo', 9000, 'norte', 'mouse')
(30, 'Ana', 'abril', 22000, 'norte', 'laptop')

In [11]:
cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)

cursor.execute("SELECT * FROM ventas;")
filas = cursor.fetchall()

for fila in filas:
    print(fila['vendedor'], fila['monto'])

Ana 15000
Luis 8000
Ana 20000
Eva 12000
Luis 9500
Ana 18000
Eva 15000
Luis 11000
Eva 9000
Ana 22000

In [14]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)

df = pd.read_sql("SELECT * FROM ventas", engine)
df

   id vendedor      mes  monto region producto
0  21      Ana    enero  15000  norte   laptop
1  22     Luis    enero   8000    sur    mouse
2  23      Ana  febrero  20000  norte   laptop
3  24      Eva    enero  12000  norte  teclado
4  25     Luis  febrero   9500    sur  monitor
5  26      Ana    marzo  18000  norte   laptop
6  27      Eva  febrero  15000  norte  monitor
7  28     Luis    marzo  11000    sur   laptop
8  29      Eva    marzo   9000  norte    mouse
9  30      Ana    abril  22000  norte   laptop

In [17]:
df_norte = pd.read_sql(
    """
    SELECT vendedor, SUM(monto) as total
    FROM ventas
    WHERE region = 'norte'
    GROUP BY vendedor
    ORDER BY total DESC
    """, engine
)

df_norte

  vendedor  total
0      Ana  75000
1      Eva  36000